/**
 * @file lib/api/index.ts
 * @description API 客户端统一导出（模块化架构）
 *
 * 所有 API 调用统一从此文件导入：
 *   import { stockApi, syncApi, axiosInstance } from '@/lib/api'
 *
 * - 各模块 API（如 stockApi）提供类型安全的方法
 * - axiosInstance 用于尚无模块覆盖的端点（通用 get/post）
 */

export { BaseApiClient, axiosInstance, API_BASE_URL } from './base'
export { AuthApiClient, authApi } from './auth'
export type { LoginRequest, LoginResponse, RegisterRequest, UpdatePasswordRequest, UpdateProfileRequest } from './auth'
export { StockApiClient, stockApi } from './stocks'
export type { StockListParams, UpdateStockRequest } from './stocks'
export { StrategyApiClient, strategyApi } from './strategies'
export type { StrategyListParams, AssignStrategyRequest } from './strategies'
export { UserApiClient, userApi } from './users'
export type { User, UserListParams, CreateUserRequest, UpdateUserRequest, UserStatistics, UserQuota } from './users'
export { SentimentApiClient, sentimentApi } from './sentiment'
export type { SyncSentimentBatchParams, TradingCalendarParams } from './sentiment'
export { MoneyflowApiClient, moneyflowApi } from './moneyflow'
export type { SyncMoneyflowParams, SyncTaskResponse, MoneyflowHsgtParams, MoneyflowMktDcParams, MoneyflowIndDcParams, MoneyflowStockDcParams, MoneyflowParams, TopMoneyflowParams } from './moneyflow'
export { HsgtTop10ApiClient, hsgtTop10Api } from './hsgt-top10'
export type { HsgtTop10Data, HsgtTop10Params, HsgtTop10Statistics } from './hsgt-top10'
export { GgtTop10ApiClient, ggtTop10Api } from './ggt-top10'
export type { GgtTop10Data, GgtTop10Params, GgtTop10Statistics } from './ggt-top10'
export { GgtDailyApiClient, ggtDailyApi } from './ggt-daily'
export type { GgtDailyData, GgtDailyParams, GgtDailyStatistics } from './ggt-daily'
export { GgtMonthlyApiClient, ggtMonthlyApi } from './ggt-monthly'
export type { GgtMonthlyData, GgtMonthlyParams, GgtMonthlyStatistics } from './ggt-monthly'
export { MarginApiClient, marginApi } from './margin'
export type { MarginParams, MarginStatistics, SyncMarginParams, MarginDetailParams, MarginDetailStatistics, MarginDetailTopParams } from './margin'
export { MarginSecsApi, marginSecsApi } from './margin-secs'
export type { MarginSecsParams, MarginSecsItem, MarginSecsStatistics, MarginSecsData, LatestMarginSecsData } from './margin-secs'
export { SlbLenApiClient, slbLenApi } from './slb-len'
export type { SlbLenParams, SlbLenData, SlbLenStatistics, SyncSlbLenParams } from './slb-len'
export { SchedulerApiClient, schedulerApi } from './scheduler'
export type { CreateScheduledTaskRequest, UpdateScheduledTaskRequest, TaskExecutionStatusResponse, TaskExecutionResult } from './scheduler'
export { CeleryTasksApiClient, celeryTasksApi } from './celery-tasks'
export type { CeleryTaskParams, CeleryTask } from './celery-tasks'
export { ConfigApiClient, configApi } from './config'
export type { DataSourceConfig, UpdateDataSourceConfigRequest, AIProviderConfig } from './config'
export { SyncApiClient, syncApi } from './sync'
export type { SyncStatusResponse, BatchSyncParams, ModuleSyncStatusResponse } from './sync'
export { ExtendedDataApiClient, extendedDataApi } from './extended-data'
export type { DateRangeParams, DailyBasicParams, HkHoldParams, LimitPricesParams, ExtendedDataSummary } from './extended-data'
export { MonitorApiClient, monitorApi } from './monitor'
export type { HealthCheckResponse, SystemMetrics, DatabaseStats, ApiPerformance, NotificationChannel } from './monitor'
export { TopListApiClient, topListApi } from './top-list'
export type { TopListParams, TopListItem, TopListStatistics } from './top-list'
export { TopInstApiClient, topInstApi } from './top-inst'
export type { TopInstParams, TopInstItem, TopInstStatistics } from './top-inst'
export { LimitListApiClient, limitListApi } from './limit-list'
export type { LimitListParams, LimitListData, LimitListStatistics } from './limit-list'
export { LimitStepApiClient, limitStepApi } from './limit-step'
export type { LimitStepParams, LimitStepData, LimitStepStatistics } from './limit-step'
export { LimitCptApiClient, limitCptApi } from './limit-cpt'
export type { LimitCptParams, LimitCptData, LimitCptStatistics } from './limit-cpt'
export { ReportRcApiClient, reportRcApi } from './report-rc'
export type { ReportRcParams, ReportRcData, ReportRcStatistics, TopRatedStock } from './report-rc'
export { StockAnnsApiClient, stockAnnsApi } from './stock-anns'
export type {
  StockAnnsItem,
  StockAnnsQueryParams,
  StockAnnsListResponse,
  StockAnnsContent,
  AnnoTypeStat,
  FetchContentEntry,
} from './stock-anns'
export { CyqPerfApiClient, cyqPerfApi } from './cyq-perf-api'
export type { CyqPerfParams, CyqPerfData, CyqPerfStatistics } from './cyq-perf-api'
export { CyqChipsApiClient, cyqChipsApi } from './cyq-chips-api'
export type { CyqChipsParams, CyqChipsData, CyqChipsStatistics } from './cyq-chips-api'
export { CcassHoldApiClient, ccassHoldApi } from './ccass-hold-api'
export type { CcassHoldParams, CcassHoldData, CcassHoldStatistics } from './ccass-hold-api'
export { CcassHoldDetailApiClient, ccassHoldDetailApi } from './ccass-hold-detail-api'
export type { CcassHoldDetailParams, CcassHoldDetailData, CcassHoldDetailStatistics } from './ccass-hold-detail-api'
export { DcMemberApiClient, dcMemberApi } from './dc-member-api'
export type { DcMemberParams, DcMemberData, DcMemberStatistics } from './dc-member-api'
export { DcIndexApiClient, dcIndexApi } from './dc-index-api'
export type { DcIndexParams, DcIndexData, DcIndexStatistics } from './dc-index-api'
export { DcDailyApiClient, dcDailyApi } from './dc-daily-api'
export type { DcDailyParams, DcDailyData, DcDailyStatistics } from './dc-daily-api'
export { HkHoldApiClient, hkHoldApi } from './hk-hold-api'
export type { HkHoldQueryParams, HkHoldData, HkHoldStatistics } from './hk-hold-api'
export { StkAuctionOApiClient, stkAuctionOApi } from './stk-auction-o'
export type { StkAuctionOParams, StkAuctionOData, StkAuctionOStatistics } from './stk-auction-o'
export { StkAuctionCApiClient, stkAuctionCApi } from './stk-auction-c'
export type { StkAuctionCParams, StkAuctionCData, StkAuctionCStatistics } from './stk-auction-c'
export { StkNineturnApiClient, stkNineturnApi } from './stk-nineturn-api'
export type { StkNineturnParams, StkNineturnData, StkNineturnStatistics, TurnSignal } from './stk-nineturn-api'
export { StkAhComparisonApiClient, stkAhComparisonApi } from './stk-ah-comparison'
export type { StkAhComparisonParams, StkAhComparisonData, StkAhComparisonStatistics, TopPremiumParams, SyncAsyncParams } from './stk-ah-comparison'
export { StkSurvApiClient, stkSurvApi } from './stk-surv-api'
export type { StkSurvParams, StkSurvData, StkSurvStatistics } from './stk-surv-api'
export { BrokerRecommendApiClient, brokerRecommendApi } from './broker-recommend-api'
export type { BrokerRecommendParams, BrokerRecommendData, BrokerRecommendStatistics } from './broker-recommend-api'
export { StkShockApiClient, stkShockApi } from './stk-shock'
export type { StkShockParams, StkShockData, StkShockStatistics } from './stk-shock'
export { StkAlertApiClient, stkAlertApi } from './stk-alert'
export type { StkAlertParams, StkAlertData, StkAlertStatistics } from './stk-alert'
export { StkHighShockApiClient, stkHighShockApi } from './stk-high-shock'
export type { StkHighShockParams, StkHighShockData, StkHighShockStatistics } from './stk-high-shock'
export { ForecastApiClient, forecastApi } from './forecast'
export type { ForecastParams, ForecastData, ForecastStatistics } from './forecast'
export { RepurchaseApiClient, repurchaseApi } from './repurchase'
export type { RepurchaseParams, RepurchaseData, RepurchaseStatistics } from './repurchase'
export { ShareFloatApiClient, shareFloatApi } from './share-float'
export type { ShareFloatParams, ShareFloatData, ShareFloatStatistics } from './share-float'
export { StkHolderNumberApiClient, stkHolderNumberApi } from './stk-holdernumber'
export type { StkHolderNumberParams, StkHolderNumberData, StkHolderNumberStatistics } from './stk-holdernumber'
export { BlockTradeApiClient, blockTradeApi } from './block-trade'
export type { BlockTradeParams, BlockTradeData, BlockTradeStatistics } from './block-trade'
export { StkHoldertradeApiClient, stkHoldertradeApi } from './stk-holdertrade-api'
export type { StkHoldertradeParams, StkHoldertradeData, StkHoldertradeStatistics, StkHoldertradeListResponse, SyncStkHoldertradeParams } from './stk-holdertrade-api'
export { IncomeApiClient, incomeApi } from './income-api'
export type { IncomeDataParams, IncomeData, IncomeStatistics } from './income-api'
export { BalancesheetApiClient, balancesheetApi } from './balancesheet-api'
export type { BalancesheetDataParams, BalancesheetData, BalancesheetStatistics } from './balancesheet-api'
export { CashflowApiClient, cashflowApi } from './cashflow-api'
export type { CashflowQueryParams, CashflowData, CashflowStatistics } from './cashflow-api'
export { ExpressApiClient, expressApi } from './express'
export type { ExpressParams, ExpressData, ExpressStatistics } from './express'
export { FinancialDataApiClient, financialDataApi } from './financial-data'
export type { DividendData, DividendStatistics, DividendParams, FinaMainbzData, FinaMainbzStatistics, FinaMainbzParams } from './financial-data'
export { SuspendApiClient, suspendApi } from './suspend'
export type { SuspendData, SuspendStatistics, SuspendListParams, SuspendSyncParams } from './suspend'
export { StkLimitDApiClient, stkLimitDApi } from './stk-limit-d'
export type { StkLimitDData, StkLimitDStatistics, StkLimitDParams } from './stk-limit-d'
export { AdjFactorApiClient, adjFactorApi } from './adj-factor-api'
export type { AdjFactorData, AdjFactorStatistics, AdjFactorParams } from './adj-factor-api'
export { NewStockApiClient, newStockApi } from './new-stock-api'
export type { NewStockData, NewStockStatistics, NewStockParams } from './new-stock-api'
export { StockListApiClient, stockListApi } from './stock-list-api'
export type { StockListData, StockListStatistics, StockListParams as StockListQueryParams } from './stock-list-api'
export { StockDailyApiClient, stockDailyApi } from './stock-daily'
export type { StockDailyData, StockDailyStatistics, StockDailyParams, SyncDailyParams, FullHistoryProgressData } from './stock-daily'
export { StockStApiClient, stockStApi } from './stock-st-api'
export type { StockStData, StockStParams, StockStStatistics, StockStResponse, StockStTypeDistribution } from './stock-st-api'
export { TradeCalApiClient, tradeCalApi } from './trade-cal-api'
export type { TradeCalParams, TradeCalData, TradeCalStatistics, TradeCalSyncParams } from './trade-cal-api'
export { SyncDashboardApiClient, syncDashboardApi } from './sync-dashboard'
export type { SyncConfig, SyncOverviewItem, SyncOverviewResponse, SyncConfigUpdate, LastTaskRecord, RedisProgress, CategoryStat } from './sync-dashboard'
export { StockAiAnalysisApiClient, stockAiAnalysisApi } from './stock-ai-analysis'
export type { StockAiAnalysisParams, StockAiAnalysisData } from './stock-ai-analysis'
export { DataOpsApiClient, dataOpsApi } from './data-ops'
export type { ClearTableParams, ClearTableResult } from './data-ops'
